### ISSUE TITLE
Deluge not seeding

### ISSUE THREAD

**Issue by she11sh0cked** [jfroment/seedbox#13]
Deluge doesn't seem to be able to seed anything. Probably because of the HTTP auth.

**Comment by she11sh0cked** [comment]
I don't really know what the issue with deluge is. I've gotten it to work in the past...
Anyway! This qBittorrent configuration works (somehow), so I'll be using it for now.
```yaml
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    volumes:
      - configqbittorrent:/config
      - downloadstorrents:/data/downloads/torrents
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - WEBUI_PORT=8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.qbittorrent-seedbox.loadbalancer.server.port=8181"

volumes:
  configqbittorrent: 
    driver: local-persist
    driver_opts:
      mountpoint: /data/config/qbittorrent
  downloadstorrents:
    driver: local-persist
    driver_opts:
      mountpoint: /data/shared/downloads/torrents
```
I would be happy to hear if anyone else has this issue though!
