### ISSUE TITLE
can't add torrent on deluge

### ISSUE THREAD

**Issue by proppyx** [jfroment/seedbox#24]
Hi, Thanks for this wonderful repository.

I have an issue with deluge. I can't add torrent. 
for example with a torrent, nothing appears and I cannot add the torrent
![image](https://user-images.githubusercontent.com/33349161/145231351-c70c89dc-7bc4-4389-8709-01e2f536cb24.png)

here are the docker logs deluge
### 
sudo docker logs deluge
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
14:59:26 [WARNING ][deluge.i18n.util           :83  ] IOError when loading translations: [Errno 2] No translation file found for domain: 'deluge'

Do you see something anormal like this warining ? Can you help me please ?

Thanks in advance.
Proppyx

**Comment by jfroment** [comment]
Hello,

I always had this warning since the beginning when I started using deluge, it seems unrelated and without any impact.
I also have this error (cannot upload a torrent), but sometimes this bug disappears and comes back...

To mitigate this, here are two workarounds:

- Use flood (bundled in this repository), which is just and UI on top of deluge, where adding torrent/magnets always works (and drag and drop into the UI is a real plus)
- Enable Auto-Add torrents in deluge plugins settings, and then upload a torrent in the dedicated watched folder (via Nextcloud for example), Deluge will automatically import it.

I thought I was the only one having this precise issue since I never found anything related in recent Deluge bugtracker's issues, but I'm keeping this ticket open, so I'll try to have a deeper look into it when I can find some time.

**Comment by Mrmel94** [comment]
Same here I opened a ticket some months ago : https://github.com/jfroment/seedbox/issues/21
And I have a friend that also have the same issue, so we're using the plugin auto add torrent because flood not working same issue as in this ticket  : https://github.com/jfroment/seedbox/issues/20

**Comment by jfroment** [comment]
Thanks for the feedback.

After another quick research, I found a solution which consists of adding custom headers for Deluge on Traefik ([here](https://github.com/binhex/arch-delugevpn/issues/152#issuecomment-569500379)). It was working before, so an update in Deluge must have added this requirement (but nothing in the release notes).

With the newly released seedbox v2, you can add your own routing rule for Traefik. I will incorporate the fix for Deluge in the next version (v2.0.1 I think).

So, *for now* the fix is the following:
* Upgrade to v2.0 first
* Edit the ``config.yaml`` file and disable traefik routing on deluge to avoid conflicts (``traefik.enabled: false`` on deluge service):
![image](https://user-images.githubusercontent.com/2869798/157267103-214bd6c4-7c06-4825-a946-d8e7673d6a7c.png)
* Add a ``deluge-rules.yaml`` file in the ``samples/custom-traefik`` directory with the following content:

```yaml
http:
  routers:
    deluge-1:
      rule: 'Host(`deluge.{{ env "TRAEFIK_DOMAIN" }}`)'
      middlewares:
        - common-auth@file
        - redirect-to-https
        - deluge-headers
      service: deluge-1
  services:
    deluge-1:
      loadBalancer:
        servers:
          - url: "http://deluge:8112" # or "http://gluetun:8112" if you enable vpn on deluge (available since v2.0)
  middlewares:
    deluge-headers:
      headers:
        customresponseheaders:
          X-Frame-Options: sameorigin
          Content-Security-Policy: frame-ancestors https://*.{{ env "TRAEFIK_DOMAIN" }}
        customrequestheaders:
          X-Frame-Options: sameorigin
          Content-Security-Policy: frame-ancestors https://*.{{ env "TRAEFIK_DOMAIN" }}
```

* Run ``./run-seedbox.sh`` and it should work now.

As said, I will add this custom headers in a bundled middleware.
When v2.0.1 is out with the fix, you will be able to remove this custom file, re-enable traefik automatic rules on deluge, and it should work out of the box.

I'm keeping this ticket opened until 2.0.1 release and waiting for your feedback. Have a nice day.
