### ISSUE TITLE
problem with gluetun config

### ISSUE THREAD

**Issue by Qbaakr** [jfroment/seedbox#53]
Hello
Does anyone know where to add a parameter to make Gluetun select a specific server?
I mean, for example, a country or a region?
sometimes it happens to me that it gets an IP from another continent
I tried both in services surfshark.yaml and in custom in the custom.yaml file
when adding server information, it throws a container error
I know you could set an end point - but then there is one specific one, and some providers, e.g. sufrshark, provide addresses in the form of a name, not in the form of an IP
Kind Regrads

**Comment by tblaudez** [comment]
Hey there,

I use Gluetun with NordVPN as a provider, I entered the informations about what continent/country/region I want to connect to within the custom `docker-compose.yaml` I use for this service.

NordVPN provides an OpenVPN configuration and many options to choose a specific server ; I don't know if Surfshark does the same.
This documentation might help you : https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md

My config looks like this :
```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Netherlands

volumes:
  configgluetun:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/gluetun
```
