### ISSUE TITLE
Plex returns 502 Bad Gateway through Traefik

### ISSUE THREAD

**Issue by Permanently** [jfroment/seedbox#71]
When accessing Plex, it seems to pop out a 502 error. I tried figuring out where it came from, and my only hypothesis is that the plex hostname can't be reached from Traefik, hence the error to begin with.
![Tabby_IytDhSLykg](https://github.com/user-attachments/assets/1876849f-fdc9-4a32-be77-fb6133a31406)
Not managed to get it working once whilst using this, unfortunately. Not that Plex doesn't work (operates fine through direct IP), just that Traefik doesn't like the `plex` hostname for whatever reason.

**Comment by tblaudez** [comment]
Did you activate the VPN option for Plex in your `config.yaml` file ?
If so, the host would not be `plex:32400` but `gluetun:32400`

On another note, can you try to access `http://plex:32400/web/index.html` instead of the webroot ?

**Comment by Permanently** [comment]
VPN is not activated — in fact, it's still nearly the default configuration.
```yaml
  - name: plex
    enabled: true
    vpn: false
    # uncomment to use custom file with specific parameters for hardware transcoding
    #customFile: plex-hardware-transcoding.yaml
    # You can also place you own file in services/custom/ and call it here like this:
    # customFile: custom/my_own_file.yaml
    traefik:
      enabled: true
      rules:
        - host: plex.${TRAEFIK_DOMAIN}
          httpAuth: false
          internalPort: 32400
```
Whether I try webroot or not is out of the question, as it's a bad address, so it'll fail either way. Regardless, I'll try for your satisfaction.
![Tabby_xbTtClyKcX](https://github.com/user-attachments/assets/967d886b-0442-409d-9435-1ff9597ffae4)
